"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-03-09 09:41:44.014329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=False),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('date_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'DELETED', name='processingstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_status'), 'dataset', ['status'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_token'), 'refresh_token', ['token'], unique=True)
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'DELETED', name='processingstatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_status'), 'vocabulary', ['status'], unique=False)
    op.create_index(op.f('ix_vocabulary_user_id'), 'vocabulary', ['user_id'], unique=False)
    op.create_table('cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_dataset_id'), 'cluster', ['dataset_id'], unique=False)
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocab_term_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vocab_term_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concept_class_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('standard_concept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('concept_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_start_date', sa.DateTime(), nullable=False),
    sa.Column('valid_end_date', sa.DateTime(), nullable=False),
    sa.Column('invalid_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vocabulary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_vocabulary_id'), 'concept', ['vocabulary_id'], unique=False)
    op.create_table('extractionjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractionjob_dataset_id'), 'extractionjob', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_extractionjob_status'), 'extractionjob', ['status'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seq_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visit_date', sa.DateTime(), nullable=True),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded', sa.DateTime(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cluster_merge_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_a_id', sa.Integer(), nullable=False),
    sa.Column('cluster_b_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_a_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['cluster_b_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_merge_suggestion_cluster_a_id'), 'cluster_merge_suggestion', ['cluster_a_id'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_cluster_b_id'), 'cluster_merge_suggestion', ['cluster_b_id'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_dataset_id'), 'cluster_merge_suggestion', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_label'), 'cluster_merge_suggestion', ['label'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_status'), 'cluster_merge_suggestion', ['status'], unique=False)
    op.create_table('sentence_segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentence_segment_record_id'), 'sentence_segment', ['record_id'], unique=False)
    op.create_table('source_to_concept_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_to_concept_map_cluster_id'), 'source_to_concept_map', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_source_to_concept_map_concept_id'), 'source_to_concept_map', ['concept_id'], unique=False)
    op.create_index(op.f('ix_source_to_concept_map_status'), 'source_to_concept_map', ['status'], unique=False)
    op.create_table('source_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_position', sa.Integer(), nullable=True),
    sa.Column('end_position', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('automatically_extracted', sa.Boolean(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('sentence_segment_id', sa.Integer(), nullable=True),
    sa.Column('linked_date_term_id', sa.Integer(), nullable=True),
    sa.Column('linked_visit_date', sa.DateTime(), nullable=True),
    sa.Column('manual_linked_visit_date', sa.Boolean(), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['cluster.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_date_term_id'], ['source_term.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sentence_segment_id'], ['sentence_segment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_term')
    op.drop_index(op.f('ix_source_to_concept_map_status'), table_name='source_to_concept_map')
    op.drop_index(op.f('ix_source_to_concept_map_concept_id'), table_name='source_to_concept_map')
    op.drop_index(op.f('ix_source_to_concept_map_cluster_id'), table_name='source_to_concept_map')
    op.drop_table('source_to_concept_map')
    op.drop_index(op.f('ix_sentence_segment_record_id'), table_name='sentence_segment')
    op.drop_table('sentence_segment')
    op.drop_index(op.f('ix_cluster_merge_suggestion_status'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_label'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_dataset_id'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_cluster_b_id'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_cluster_a_id'), table_name='cluster_merge_suggestion')
    op.drop_table('cluster_merge_suggestion')
    op.drop_table('record')
    op.drop_index(op.f('ix_extractionjob_status'), table_name='extractionjob')
    op.drop_index(op.f('ix_extractionjob_dataset_id'), table_name='extractionjob')
    op.drop_table('extractionjob')
    op.drop_index(op.f('ix_concept_vocabulary_id'), table_name='concept')
    op.drop_table('concept')
    op.drop_index(op.f('ix_cluster_dataset_id'), table_name='cluster')
    op.drop_table('cluster')
    op.drop_index(op.f('ix_vocabulary_user_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_status'), table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_refresh_token_token'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_dataset_status'), table_name='dataset')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###

