"""add vocabulary status fields

Revision ID: 003
Revises: 002
Create Date: 2026-01-06 17:55:20.873987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define the enum type at module level for reuse
vocabularystatus_enum = postgresql.ENUM(
    "PENDING", "PROCESSING", "DONE", "FAILED", name="vocabularystatus"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS concept_staging")
    op.alter_column(
        "dataset",
        "labels",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "source_to_concept_map",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "source_to_concept_map",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "source_to_concept_map",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=None,
        existing_nullable=False,
    )

    # Create the enum type FIRST
    vocabularystatus_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "vocabulary", sa.Column("status", vocabularystatus_enum, nullable=False)
    )
    op.add_column("vocabulary", sa.Column("started_at", sa.DateTime(), nullable=True))
    op.add_column("vocabulary", sa.Column("finished_at", sa.DateTime(), nullable=True))
    op.add_column(
        "vocabulary",
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(
        op.f("ix_vocabulary_status"), "vocabulary", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vocabulary_status"), table_name="vocabulary")
    op.drop_column("vocabulary", "error_message")
    op.drop_column("vocabulary", "finished_at")
    op.drop_column("vocabulary", "started_at")
    op.drop_column("vocabulary", "status")
    op.alter_column(
        "source_to_concept_map",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "source_to_concept_map",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        server_default=sa.text("CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    op.alter_column(
        "source_to_concept_map",
        "status",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("'pending'::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "dataset",
        "labels",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.create_table(
        "concept_staging",
        sa.Column("vocab_term_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("vocab_term_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("domain_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("concept_class_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("standard_concept", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("concept_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("valid_start_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("valid_end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("invalid_reason", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
