"""add extraction job

Revision ID: 004
Revises: 003
Create Date: 2026-01-16 08:48:07.070993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extractionjob',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractionjob_dataset_id'), 'extractionjob', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_extractionjob_status'), 'extractionjob', ['status'], unique=False)
    op.drop_index(op.f('ix_vocabulary_status'), table_name='vocabulary')
    op.drop_column('vocabulary', 'status')
    op.drop_column('vocabulary', 'error_message')
    op.drop_column('vocabulary', 'finished_at')
    op.drop_column('vocabulary', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('vocabulary', sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('vocabulary', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vocabulary', sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='vocabularystatus'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_vocabulary_status'), 'vocabulary', ['status'], unique=False)
    op.drop_index(op.f('ix_extractionjob_status'), table_name='extractionjob')
    op.drop_index(op.f('ix_extractionjob_dataset_id'), table_name='extractionjob')
    op.drop_table('extractionjob')
    # ### end Alembic commands ###

