"""change Vocabulary table

Revision ID: 005
Revises: 004
Create Date: 2026-01-21 13:18:20.072372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '005'
down_revision: Union[str, None] = '004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_merge_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cluster_a_id', sa.Integer(), nullable=False),
    sa.Column('cluster_b_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_a_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['cluster_b_id'], ['cluster.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_merge_suggestion_cluster_a_id'), 'cluster_merge_suggestion', ['cluster_a_id'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_cluster_b_id'), 'cluster_merge_suggestion', ['cluster_b_id'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_dataset_id'), 'cluster_merge_suggestion', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_label'), 'cluster_merge_suggestion', ['label'], unique=False)
    op.create_index(op.f('ix_cluster_merge_suggestion_status'), 'cluster_merge_suggestion', ['status'], unique=False)
    op.drop_column('vocabulary', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_vocabulary_status'), table_name='vocabulary')
    op.add_column('vocabulary', sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_cluster_merge_suggestion_status'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_label'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_dataset_id'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_cluster_b_id'), table_name='cluster_merge_suggestion')
    op.drop_index(op.f('ix_cluster_merge_suggestion_cluster_a_id'), table_name='cluster_merge_suggestion')
    op.drop_table('cluster_merge_suggestion')
    # ### end Alembic commands ###

