"""add status to Vocabulary table

Revision ID: 006
Revises: 005
Create Date: 2026-01-21 14:57:14.949686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabulary', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'DELETED', name='vocabularystatus'), nullable=False, server_default='DONE'))
    op.add_column('vocabulary', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_vocabulary_status'), 'vocabulary', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocabulary_status'), table_name='vocabulary')
    op.drop_column('vocabulary', 'error_message')
    op.drop_column('vocabulary', 'status')
    # ### end Alembic commands ###

