"""add manual visit date

Revision ID: 013
Revises: 012
Create Date: 2026-02-26 11:22:15.411822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '013'
down_revision: Union[str, None] = '012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_term', sa.Column('manual_linked_visit_date', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    # Drop the default first (it references the old enum type)
    op.execute("ALTER TABLE vocabulary ALTER COLUMN status DROP DEFAULT")
    # Cast vocabulary.status from vocabularystatus to processingstatus
    op.execute("ALTER TABLE vocabulary ALTER COLUMN status TYPE processingstatus USING status::text::processingstatus")
    # Drop the old enum type
    op.execute("DROP TYPE IF EXISTS vocabularystatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate vocabularystatus enum and cast back
    op.execute("CREATE TYPE vocabularystatus AS ENUM ('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'DELETED')")
    op.execute("ALTER TABLE vocabulary ALTER COLUMN status TYPE vocabularystatus USING status::text::vocabularystatus")
    op.execute("ALTER TABLE vocabulary ALTER COLUMN status SET DEFAULT 'DONE'::vocabularystatus")
    op.drop_column('source_term', 'manual_linked_visit_date')
    # ### end Alembic commands ###